# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

name: Publish On Release

on:
  # trigger when a release or pre-release is published
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

env:
  test-requires: "[test,extra]"
  test-dir: test
  pytest-args: >-
    -rap
  build-python-version: "3.7"

# todo: caution: packages are published to test pypi
jobs:

  tests-pip:
    name: Tests (pip, Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade wheel setuptools
        pip install ".${{ env.test-requires }}"
    - name: Run tests
      run: |
        pytest ${{ env.pytest-args }} ${{ env.test-dir }}

  package-publish-pypi:
    name: Package and publish to pypi.org
    needs: tests-pip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.build-python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.build-python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build wheel setuptools twine
      - name: Build package (source distribution and wheel)
        run: |
          python -m build --sdist --wheel
      - name: Verify package
        run: |
          twine check dist/* --strict
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true
          repository_url: https://test.pypi.org/legacy/
