# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

name: Ubuntu Test

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  test-requires: "[test,extra]"
  test-dir: test
  pytest-args: >-
    -rap
  build-python-version: "3.7"

jobs:

  test_building_package:
    name: Test building package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.build-python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.build-python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build wheel setuptools twine
      - name: Build package (source distribution and wheel)
        run: |
          python -m build --sdist --wheel
      - name: Show package contents
        run: |
          ls -alh dist
          echo "========== .tar.gz =========="
          tar tf dist/*.tar.gz
          echo "========== .whl =========="
          unzip -l dist/*.whl
      - name: Verify package
        run: |
          twine check dist/* --strict
